### ISSUE TITLE
[Issue] Off-centre

### ISSUE THREAD

**Issue by ethe1** [peterprd/Grupi-reports-and-request#1]
Grupi seems to be off-centre when viewed on both the lock screen and notification centre. Doesn’t seem to be an issue regarding other tweaks as even when Grupi is the only one enabled, the tweak is still misaligned.
![490EA797-932F-481B-80D3-A2D032E95CDE](https://user-images.githubusercontent.com/59261807/72198429-09a68900-3492-11ea-814a-b282ab4b859e.png)

**Comment by s8ngyu** [comment]
Added to TODO list!

**Comment by ethe1** [comment]
Resolved
