### ISSUE TITLE
[Request] Show latest notification

### ISSUE THREAD

**Issue by ethe1** [peterprd/Grupi-reports-and-request#4]
Do you think it would be possible to implement something similar to 'Axon' where there was an option to show the latest notification? Currently when you do receive a message, there's not much of a differentiating factor as when the screen lights up, all you see is an extra group of notifications. So this request is essentially asking for that if you receive a notification from a particular app, that group will be then opened allowing you to see the newly received message with ease, and once you close out of the notification centre or unlock your screen, it will then close it self, requiring another tap to open it. Thanks

**Comment by s8ngyu** [comment]
Ok, I'll try.

**Comment by ethe1** [comment]
Thanks, I wish you the best! Also, if it doesn’t seem feasible, just having Grupi always show the latest notification would totally be fine.
